spring.application.name=learn-spring-ai

spring.ai.openai.api-key=lmstudio
spring.ai.openai.base-url=http://localhost:1234/v1
spring.ai.openai.model=qwen/qwen3.5-9b
spring.ai.openai.chat.reasoning-effort=low
# Local vector database
#spring.ai.vectorstore.
# Embeddings
spring.ai.openai.embedding.model=text-embedding-qwen3-embedding-0.6b
spring.ai.openai.embedding.dimensions=512
spring.ai.openai.embedding.api-key=lmstudio
# Logging config
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
