spring.application.name=learn-spring-ai

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=https://api.openai.com/v1
spring.ai.openai.model=gpt-5-nano
spring.ai.openai.chat.reasoning-effort=low
# MCP config
spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json
spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.type=sync
spring.ai.mcp.client.enabled=true
# Vector Store config
spring.ai.vectorstore.pinecone.api-key=${PINECONE_API_KEY}
spring.ai.vectorstore.pinecone.index-name=soaring-ash
#spring.ai.vectorstore.pinecone.namespace=
spring.ai.openai.embedding.model=text-embedding-3-small
spring.ai.openai.embedding.dimensions=512
spring.ai.openai.embedding.api-key=${OPENAI_EMBEDDING_API_KEY}
# swagger ui
springdoc.swagger-ui.path=/